# -*- coding: utf-8 -*-
"""NER_medical_spacy.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://drive.google.com/file/d/1hAkZvNhDoK6FlXDaeWM0YTo1N6gDDM4Y/view?usp=drive_link
"""

# This project is the proof of concept for Medical NER, based on Spacy
# File created with original ipynb in COLAB, adopted to development with PyCharm
# To be used for new medical NER model creation and calculation

import os
import spacy
from spacy.cli.train import train
import json

# open the data with annotated instances for model training
print(os.getcwd())  # check current directory
with open('dataset/Corona2.json', 'r') as f:
    data = json.load(f)

data['examples'][0].keys()

print(data['examples'][0]['content'])
print(data['examples'][0]['annotations'][0])

# creating training data object from annotations file
training_data = []
for example in data['examples']:
    temp_dict = {}
    temp_dict['text'] = example['content']
    temp_dict['entities'] = []
    for annotation in example['annotations']:
        start = annotation['start']
        end = annotation['end']
        label = annotation['tag_name'].upper()
        temp_dict['entities'].append((start, end, label))
    training_data.append(temp_dict)

training_data[0]['entities']

training_data[0]['text'][360:371]

from spacy.tokens import DocBin
from tqdm import tqdm

# prepare the model for training
nlp = spacy.blank("en") # load a new spacy model
doc_bin = DocBin()

from spacy.util import filter_spans

for training_example in tqdm(training_data):
    text = training_example['text']
    labels = training_example['entities']
    doc = nlp.make_doc(text)
    ents = []
    for start, end, label in labels:
        span = doc.char_span(start, end, label=label, alignment_mode="contract")
        if span is None:
            print("Skipping entity")
        else:
            ents.append(span)
    filtered_ents = filter_spans(ents)
    doc.ents = filtered_ents
    doc_bin.add(doc)

doc_bin.to_disk("train.spacy")

# To generate the config file
#! python -m spacy init config config.cfg --lang en --pipeline ner --optimize efficiency
#! python -m spacy train config.cfg --output ./ --paths.train ./train.spacy --paths.dev ./train.spacy
train("./config.cfg", "output", overrides={"paths.train": "./train.spacy", "paths.dev": "./dev.spacy"})

#nlp_trained_model = spacy.load("model-best")
nlp_trained_model = spacy.load("model-last")

doc = nlp_trained_model('''
The patient was prescribed Aspirin for their heart condition.
The doctor recommended Ibuprofen to alleviate the patient's headache.
The patient is suffering from diabetes, and they need to take Metformin regularly.
After the surgery, the patient experienced some post-operative complications, including infection.
The patient is currently on a regimen of Lisinopril to manage their high blood pressure.
The antibiotic course for treating the bacterial infection should be completed as prescribed.
The patient's insulin dosage needs to be adjusted to better control their blood sugar levels.
The physician suspects that the patient may have pneumonia and has ordered a chest X-ray.
The patient's cholesterol levels are high, and they have been advised to take Atorvastatin.
The allergy to penicillin was noted in the patient's medical history.
''')

doc1 = nlp_trained_model('''
Severe Acute Respiratory Syndrome Coronavirus-2 (SARS-CoV-2), the causative pathogen for the COVID-19, first emerged in Wuhan, China, in December 2019 and by March 2020, it was declared a pandemic.
COVID-19 pandemic has overburdened healthcare systems in most countries and has led to massive economic losses.
SARS-CoV-2 transmission typically occurs by respiratory droplets.
The average incubation period is 6.4 days and presenting symptoms typically include fever, cough, dyspnea, myalgia or fatigue.
While the majority of patients tend to have a mild illness, a minority of patients develop severe hypoxia requiring hospitalization and mechanical ventilation.
Management is mostly supportive. However, several direct anti-viral agents, and immunomodulatory therapy with steroids and various cytokine blockers seem promising in early results.
However, an effective vaccine has been established, which will help curb the pandemic.
''')

spacy.displacy.render(doc1, style="ent", jupyter=True) # display in Jupyter

